### ISSUE TITLE
Lotus3 mod

### ISSUE THREAD

**Issue by patuwwy** [jhalme/webaudio-mod-player#3]
When playing module from LOTUS3 game, module quiality drops at ~0:50 
mod:
http://patrykfalba.eu/entries/lotus3/music/l3_cd3_lotus3.mod

player:
http://patrykfalba.eu/entries/lotus3/ (with added analyser in player)

Module is playing ok in winamp.

**Comment by patuwwy** [comment]
The problem is caused by E0x effect in song. 
As suggested by the author, I disabled setting filter in effect_t0_e0 function.

Thanks

**Comment by sagamusix** [comment]
The effect_t0_e0 implementation is actually wrong, E0x enables the LED filter if x is even and disables it if x is odd. In particular, E00 enables the filter and E01 disables it. If implemented correctly, the Lotus music plays correctly.

**Comment by jhalme** [comment]
Changed the Protracker E0x effect to only look at the least significant bit of the parameter.

**Comment by sagamusix** [comment]
Looking at the code, it's still not quite correct: The filter should be *disabled* if the bit is set. Also, the " // look ahead at very first row to see if filter gets enabled" (line 280) needs to be updated accordingly.

**Comment by jhalme** [comment]
Ah, damnit. Ok, should be fixed now.

https://mod.haxor.fi/Patrick_Phelan/l3_cd3_lotus3.mod
