### ISSUE TITLE
I can help you with the "spaghetti code"!

### ISSUE THREAD

**Issue by chris-l** [jhalme/webaudio-mod-player#4]
After reading [this](https://github.com/jhalme/webaudio-mod-player/blob/master/js/pt.js#L5-L6), I thought  that I could help you with that.

I could clean up the code, following good practices, adding spaces, etc. and then, I'll add a JavaScript linter. At the same time, that would be without changing too much the structure of the code, so you can still find it familiar. After that, I'll send you a pull request.

Are you interested? (I'm asking first because it will take some time to do it; so it would be a waste if you are not interested)

**Comment by jhalme** [comment]
Thanks for the offer. However, I'm currently working on adding support for S3M and XM formats so doing cleanup/refactoring at this point may cause some problems with merging as both branches would bring substantial changes to the code.

I'll push my changes to the project once I have reasonable functionality in place for both formats. After that, it may be a good idea to start cleaning things up a bit.

**Comment by chris-l** [comment]
Sure, let me know when you are done to fork it ;)

**Comment by jhnsnc** [comment]
It's awesome to see support for additional formats getting added! Is that work basically done?
If there are no significant changes pending, I would like to see if I can find time to make some improvements.

**Comment by jhalme** [comment]
I think the most significant changes are now in the codebase. At this point it's mostly fixing various playback and file loader bugs and optimizing for speed. XM player code still has several missing features but adding those would not alter the general structure of the code.
